-- @nestjs/outbox: PostgresOutboxStore's schema "nest_outbox", from version 0 to 1.
-- Run it in one transaction.

CREATE SCHEMA IF NOT EXISTS "nest_outbox";
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "nest_outbox".migrations (
  version integer PRIMARY KEY,
  name text NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "nest_outbox".messages (
  seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id text NOT NULL UNIQUE,
  topic text NOT NULL,
  payload jsonb,
  headers jsonb NOT NULL,
  key text,
  created_at bigint NOT NULL,
  available_at bigint NOT NULL,
  attempts integer NOT NULL DEFAULT 0,
  last_error text,
  history jsonb NOT NULL DEFAULT '[]',
  lease_owner text,
  lease_until bigint
);
--> statement-breakpoint
CREATE TABLE "nest_outbox".dead_letters (
  id text PRIMARY KEY,
  seq bigint NOT NULL,
  topic text NOT NULL,
  payload jsonb,
  headers jsonb NOT NULL,
  key text,
  created_at bigint NOT NULL,
  attempts integer NOT NULL,
  last_error text,
  history jsonb NOT NULL,
  reason text NOT NULL,
  failed_at bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "nest_outbox".inbox (
  consumer text NOT NULL,
  message_id text NOT NULL,
  processed_at bigint NOT NULL,
  PRIMARY KEY (consumer, message_id)
);
--> statement-breakpoint
CREATE INDEX messages_key_seq ON "nest_outbox".messages (key, seq) WHERE key IS NOT NULL;
--> statement-breakpoint
CREATE INDEX dead_letters_topic_failed_at ON "nest_outbox".dead_letters (topic, failed_at);
--> statement-breakpoint
CREATE INDEX inbox_processed_at ON "nest_outbox".inbox (processed_at);
--> statement-breakpoint
INSERT INTO "nest_outbox".migrations (version, name) VALUES (1, 'initial');
--> statement-breakpoint
-- Stop the legacy relay before applying this migration. Keep historical rows
-- for reconciliation: processed_at was written before delivery in the old relay.
INSERT INTO "nest_outbox".messages
  (id, topic, payload, headers, created_at, available_at)
SELECT id::text, event_type, payload, '{}'::jsonb,
  (extract(epoch FROM occurred_at AT TIME ZONE 'UTC') * 1000)::bigint,
  (extract(epoch FROM occurred_at AT TIME ZONE 'UTC') * 1000)::bigint
FROM public.outbox_messages
WHERE processed_at IS NULL
ORDER BY occurred_at, id
ON CONFLICT (id) DO NOTHING;
