import { describe, expect, it } from "vitest";
import {
  isLegacyPasswordHash,
  verifyLegacyPassword,
} from "./legacy-password.js";

// Generated by better-auth/crypto.hashPassword("cafe\u0301-\uff30assword-123")
// before removing Better Auth; the verifier must remain compatible independently.
const LEGACY_PASSWORD_HASH =
  "2d8361dcc1b5ce89a168f04fc4c3ea59:8796e28950e3bf5f130c07d59fe0180030621ee8df901175083a8efe2ced807e51427b657156a8febef39e84f01dc622cf7f34738e5d75c2674f04b77fc4e636";

describe("verifyLegacyPassword", () => {
  it.each(["cafe\u0301-\uff30assword-123", "caf\u00e9-Password-123"])(
    "verifies an existing password after Unicode normalization: %s",
    async (password) => {
      // Given
      const hash = LEGACY_PASSWORD_HASH;

      // When
      const verified = await verifyLegacyPassword(password, hash);

      // Then
      expect(verified).toBe(true);
    },
  );

  it("refuses an incorrect password", async () => {
    // Given
    const password = "caf\u00e9-Password-124";

    // When
    const verified = await verifyLegacyPassword(password, LEGACY_PASSWORD_HASH);

    // Then
    expect(verified).toBe(false);
  });

  it.each([
    "",
    "missing-separator",
    "a".repeat(32) + ":" + "b".repeat(126),
    "a".repeat(30) + ":" + "b".repeat(128),
    "g".repeat(32) + ":" + "b".repeat(128),
    LEGACY_PASSWORD_HASH + ":extra",
    LEGACY_PASSWORD_HASH + "\n",
    "a".repeat(100_000) + ":" + "b".repeat(128),
  ])("refuses a malformed legacy hash", async (hash) => {
    // Given
    const password = "caf\u00e9-Password-123";

    // When
    const verified = await verifyLegacyPassword(password, hash);

    // Then
    expect(verified).toBe(false);
  });

  it.each(["", "a".repeat(4097), "\ufdfa".repeat(256)])(
    "refuses an empty or oversized normalized password",
    async (password) => {
      // Given
      const hash = LEGACY_PASSWORD_HASH;

      // When
      const verified = await verifyLegacyPassword(password, hash);

      // Then
      expect(verified).toBe(false);
    },
  );
});

describe("isLegacyPasswordHash", () => {
  it("recognizes the existing Better Auth encoding", () => {
    // Given
    const hash = LEGACY_PASSWORD_HASH;

    // When
    const recognized = isLegacyPasswordHash(hash);

    // Then
    expect(recognized).toBe(true);
  });

  it("leaves native NestJS password hashes to the official hasher", () => {
    // Given
    const hash = "$scrypt$ln=17,r=8,p=1$nativeSalt$nativeHash";

    // When
    const recognized = isLegacyPasswordHash(hash);

    // Then
    expect(recognized).toBe(false);
  });
});
